spring:
  profile:
    active:
    - dev

---
server:
  port: 8201
spring:
  profile: dev
  application:
    name: mymicroserver-auth-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
server:
  port: 8202
spring:
  profile: test
  application:
    name: mymicroserver-auth-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

---